### ISSUE TITLE
Unable to load trackers after upgrading to HA 2023.5

### ISSUE THREAD

**Issue by burnsie-la** [formatBCE/Format-BLE-Tracker#1]
After upgrading to HA 2023.5 I can no longer load the format_ble_tracker integration with my beacons.  I have tried removing and re-adding the beacon, but the problem persists.

Any suggestions?  Relevant log entries are below:

![image](https://user-images.githubusercontent.com/46924973/236622430-a26f98fc-19ba-4805-8324-53bcce7f899e.png)

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/format_ble_tracker/__init__.py:64
Integration: Format BLE Tracker (documentation, issues)
First occurred: 12:30:56 PM (3 occurrences)
Last logged: 12:51:54 PM

Error setting up entry Alan's Android Phone for format_ble_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/format_ble_tracker/__init__.py", line 64, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

2023-05-06 12:30:45.298 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration format_ble_tracker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-06 12:30:56.932 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alan's Android Phone for format_ble_tracker
File "/config/custom_components/format_ble_tracker/__init__.py", line 64, in async_setup_entry

**Comment by formatBCE** [comment]
Ok, I procrastinated on that too long.
Will fix asap.

**Comment by formatBCE** [comment]
Enjoy version 0.0.8.
